### ISSUE TITLE
IBus IME not working with electron app

### ISSUE THREAD

**Issue by chenzhiwei** [flathub/io.atom.electron.BaseApp#4]
Tested with the latest Slack and Atom editor, and use following command can make ibus IME work, please take a look at this issue.

```
 flatpak run with --env=GTK_IM_MODULE=xim io.atom.Atom
```

Related issue:

1. Atom: https://github.com/flathub/io.atom.Atom/issues/6
2. Slack: https://github.com/flathub/com.slack.Slack/issues/21
3. VS code: https://github.com/flathub/com.visualstudio.code/issues/24

cc @fujiwarat Don't know why `GTK_IM_MODULE=ibus` does not work, could you comment on this?

Thanks!

**Comment by juhp** [comment]
Is it possible to add the ibus gtk2 immodule to this BaseApp?

**Comment by TingPing** [comment]
Well you are reporting it doesn't work with Gtk3 either, so its probably an Electron bug anyway.

**Comment by juhp** [comment]
Discord works for me though, surprisingly - not sure why though.
(See https://github.com/flatpak/flatpak/issues/1671#issuecomment-436943648)

**Comment by TingPing** [comment]
I think that eliminates GTK being relevant, Discord is GTK2 and has no ibus module.

**Comment by juhp** [comment]
Not sure, maybe we should just ignore Discord for now if it is an anomaly.

**Comment by fujiwarat** [comment]
I evaluated Atom and visualstudio in https://github.com/ibus/ibus/issues/1991 .
The pure electron application works fine with ibus as I commented the issue.
Note: they uses ibus in org.freedesktop.Sdk instead of org.freedesktop.Platform and need to port the ibus fix to the Flatpak.
So I think this can be closed.

**Comment by fujiwarat** [comment]
If you use Fedora, I put a fixed binary for the testing ; https://fujiwara.fedorapeople.org/ibus/20190108/
