### ISSUE TITLE
Udev library seems to have different name on 19.08 branch

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.atom.electron.BaseApp#7]
I am trying to update the freedesktop runtime to 19.08 on my [BlueJeans](https://github.com/flathub/com.bluejeans.BlueJeans) Flatpak, unfortunately it [does not work](https://github.com/flathub/com.bluejeans.BlueJeans/issues/8), because `libudev.so.0` does not seem to be present in the runtime, only `libudev.so.1`. Not sure if this is a fd runtime issue or a electron BaseApp one, so I am reporting it here.

**Comment by Erick555** [comment]
@AsciiWolf are you sure you updated both runtime and baseapp? Nothing should use `libudev.so.0` unless it was build against older runtime/baseapp.

**Comment by AsciiWolf** [comment]
Yeah, I am pretty sure I did update both the runtime and baseapp version. I tried it multiple times, still the same issue.

**Comment by Erick555** [comment]
@AsciiWolf bluejeans-bin from upstream package is linked against `libudev.so.0`. What you need is to create symlink like https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bluejeans#n89

**Comment by Erick555** [comment]
@AsciiWolf as this was app issue which is now fixed you may close this.
